package discrete_mathematics;

/**
 *
 * @author Aman
 */
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
public class Expression_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Expression_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel_title = new javax.swing.JLabel();
        jLabel_expr = new javax.swing.JLabel();
        jLabel_pre = new javax.swing.JLabel();
        jLabel_post = new javax.swing.JLabel();
        jLabel_conj = new javax.swing.JLabel();
        jLabel_disj = new javax.swing.JLabel();
        jTextField_expr = new javax.swing.JTextField();
        jTextField_pre = new javax.swing.JTextField();
        jTextField_post = new javax.swing.JTextField();
        jTextField_conj = new javax.swing.JTextField();
        jTextField_disj = new javax.swing.JTextField();
        jButton_convert_exp = new javax.swing.JButton();
        jButton_convert_tab = new javax.swing.JButton();
        jButton_rewrite = new javax.swing.JButton();
        jLabel_func1 = new javax.swing.JLabel();
        jLabel_func2 = new javax.swing.JLabel();
        jLabel_func3 = new javax.swing.JLabel();
        jLabel_func4 = new javax.swing.JLabel();
        jScrollPane_table = new javax.swing.JScrollPane();
        jTextArea_table = new javax.swing.JTextArea();
        jLabel_table = new javax.swing.JLabel();
        jLabel_designer = new javax.swing.JLabel();
        jLabel_functions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Discrete Mathematics");
        setName("frameUserLogin"); // NOI18N
        setSize(new java.awt.Dimension(1200, 850));

        jLabel_title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel_title.setText("Logical Expression Calculator");

        jLabel_expr.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel_expr.setText("Logical expression:");

        jLabel_pre.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel_pre.setText("Prefix expression:");

        jLabel_post.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel_post.setText("Postfix expression:");

        jLabel_conj.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel_conj.setText("Conjunctive form:");

        jLabel_disj.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel_disj.setText("Disjunctive form:");

        jTextField_expr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_pre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_post.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_conj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_disj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton_convert_exp.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton_convert_exp.setText("Convert from expression");
        jButton_convert_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_convert_expActionPerformed(evt);
            }
        });

        jButton_convert_tab.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton_convert_tab.setText("Convert from table");
        jButton_convert_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_convert_tabActionPerformed(evt);
            }
        });

        jButton_rewrite.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jButton_rewrite.setText("Rewrite");
        jButton_rewrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rewriteActionPerformed(evt);
            }
        });

        jLabel_func1.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jLabel_func1.setText("1.Print the prefix and postfix expression from a logical expression ");

        jLabel_func2.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jLabel_func2.setText("2.Print the truth table from a logical expression");

        jLabel_func3.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jLabel_func3.setText("3.Print the logical expression from a truth table");

        jLabel_func4.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jLabel_func4.setText("4.Print the principal conjunctive and disjunctive normal form from a logical expression");

        jTextArea_table.setColumns(20);
        jTextArea_table.setRows(5);
        jScrollPane_table.setViewportView(jTextArea_table);

        jLabel_table.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel_table.setText("Truth table:");

        jLabel_designer.setFont(new java.awt.Font("Indie Flower", 0, 14)); // NOI18N
        jLabel_designer.setText("----Desinged by Aman");

        jLabel_functions.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        jLabel_functions.setText("Functions:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_functions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel_title)
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_func2)
                                    .addComponent(jLabel_func1)
                                    .addComponent(jLabel_func3)
                                    .addComponent(jLabel_func4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_pre)
                                            .addComponent(jLabel_post)
                                            .addComponent(jLabel_expr)
                                            .addComponent(jLabel_conj)
                                            .addComponent(jLabel_disj))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_expr, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_post, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_conj, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_disj, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(99, 99, 99))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_convert_exp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_convert_tab)
                                        .addGap(70, 70, 70)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane_table, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_table)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_rewrite, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_designer)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_functions)
                        .addGap(20, 20, 20)))
                .addComponent(jLabel_func1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_func2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_func3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_func4)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_expr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_expr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_table, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_post, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_post, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_conj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_conj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_disj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_disj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane_table, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel_designer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_rewrite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_convert_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_convert_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_convert_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_convert_expActionPerformed
        String s=jTextField_expr.getText();
        if(!Discrete_Mathematics.check(s)){
            jTextField_pre.setText("Error,invalid input  (。﹏。)");
            jTextField_post.setText("Error,invalid input  (。﹏。)");
            jTextField_conj.setText("Error,invalid input  (。﹏。)");
            jTextField_disj.setText("Error,invalid input  (。﹏。)");
            jTextArea_table.setText("Error,invalid input  (。﹏。)");
        }
        else{
            jTextField_pre.setText(Discrete_Mathematics.prefix(s));
            jTextField_post.setText(Discrete_Mathematics.postfix(s));
            jTextField_conj.setText(Discrete_Mathematics.conjunctive(s));
            jTextField_disj.setText(Discrete_Mathematics.disjunctive(s));
            jTextArea_table.setText(Discrete_Mathematics.table(s));
        }
    }//GEN-LAST:event_jButton_convert_expActionPerformed

    private void jButton_rewriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rewriteActionPerformed
        jTextField_expr.setText("");
        jTextField_pre.setText("");
        jTextField_post.setText("");
        jTextField_conj.setText("");
        jTextField_disj.setText("");
        jTextArea_table.setText("");
    }//GEN-LAST:event_jButton_rewriteActionPerformed

    private void jButton_convert_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_convert_tabActionPerformed
        ArrayList l=new ArrayList();
        for(int i = 0; i < jTextArea_table.getRows(); i++){
            try{
                l.add(jTextArea_table.getText(jTextArea_table.getLineStartOffset(i),jTextArea_table 
                                .getLineEndOffset(i) 
                                - jTextArea_table.getLineStartOffset(i)));
                    } catch (BadLocationException ex) {
                Logger.getLogger(Expression_Calculator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTextField_expr.setText(Discrete_Mathematics.build(l));
        jTextField_pre.setText("");
        jTextField_post.setText("");
        jTextField_conj.setText("");
        jTextField_disj.setText("");
    }//GEN-LAST:event_jButton_convert_tabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expression_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expression_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expression_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expression_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expression_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton_convert_exp;
    private javax.swing.JButton jButton_convert_tab;
    private javax.swing.JButton jButton_rewrite;
    private javax.swing.JLabel jLabel_conj;
    private javax.swing.JLabel jLabel_designer;
    private javax.swing.JLabel jLabel_disj;
    private javax.swing.JLabel jLabel_expr;
    private javax.swing.JLabel jLabel_func1;
    private javax.swing.JLabel jLabel_func2;
    private javax.swing.JLabel jLabel_func3;
    private javax.swing.JLabel jLabel_func4;
    private javax.swing.JLabel jLabel_functions;
    private javax.swing.JLabel jLabel_post;
    private javax.swing.JLabel jLabel_pre;
    private javax.swing.JLabel jLabel_table;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JScrollPane jScrollPane_table;
    private javax.swing.JTextArea jTextArea_table;
    private javax.swing.JTextField jTextField_conj;
    private javax.swing.JTextField jTextField_disj;
    private javax.swing.JTextField jTextField_expr;
    private javax.swing.JTextField jTextField_post;
    private javax.swing.JTextField jTextField_pre;
    // End of variables declaration//GEN-END:variables
}
